---
- hosts: all
  roles:
     - { role: docker-container, container: "{{ postgres }}", tags: [env, pg] }
     - { role: docker-container, container: "{{ rabbitmq }}", tags: [env, rmq] }
     - { role: django-manage, tags: [env, manage] }
     - { role: docker-container, container: "{{ the_tale }}", tags: app }
