
tt_domain: local.the-tale
tt_test_enviroment: True
tt_log_level: debug
tt_site_workers: 1
tt_install_nginx: True
tt_install_postfix: True

tt_postfix_virtual_aliases: {}

tt_authorized_keys: []

tt_services:
  the_tale:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/dext/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/deworld/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/questgen/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_logic/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_calendar/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/the_tale/"}
  tt_diary:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_diary/"}
  tt_personal_messages:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/rels/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_personal_messages/"}
  tt_storage:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_storage/"}
  tt_market:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_market/"}
  tt_soft_currency:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_bank/"}
  tt_players_timers:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_timers/"}
    custom:
        secret: test.secret
        sleep_if_no_timers_interval: 0.1
        delay_before_callback_retry: 31536000  # do not spam test site (it can be stopped at all)
                                               # if timer processing required - restart service
        types:
          0:
            url: http://localhost:8000/game/cards/tt/take-card-callback
            postprocess_type: restart
  tt_personal_impacts:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}
  tt_crowd_impacts:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}
  tt_job_impacts:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}
  tt_fame_impacts:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_impacts/"}

  tt_game_chronicle:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_events_log/"}

  tt_clans_chronicle:
    packages:
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_web/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_protocol/"}
      - {editable: True, extra: "-e", name: "/mnt/repos/the-tale/src/tt_events_log/"}

tt_RAM: 4096
tt_postgresql_maintenance_work_mem: 32MB # 256MB
tt_postgresql_max_worker_processes: 1    # ???? ~ cores number div 2? or just cores number

tt_backups: None

tt_datadog_api_key: None